version: "3.8"

networks:
  database_network:
    name: theDjangoNetwork
    driver: bridge

services:
  database:
    image: postgres
    build:
      context: ./
      dockerfile: Dockerfile
    hostname: tutorPostgres
    restart: always
    env_file:
      - ./config/dev_database.env
    networks:
      - database_network
    volumes:
      - ./database_test/pg_data:/dev_database/
    ports:
      - "5438:5432"
    container_name: 'tutorDB'